<html>
<body>
<pre>
<h1>ビルドのログ</h1>
<h3>
--------------------構成 : BananaCE - Win32 (WCE ARMV4) Release--------------------
</h3>
<h3>コマンド ライン</h3>
一時ファイル "C:\DOCUME~1\RTI~1.KAE\LOCALS~1\Temp\RSP80.tmp" を作成し、次の内容を記録します
[
/nologo /W3 /GX /D _WIN32_WCE=420 /D "WIN32_PLATFORM_PSPC=400" /D "ARM" /D "_ARM_" /D "ARMV4" /D UNDER_CE=420 /D "UNICODE" /D "_UNICODE" /D "NDEBUG" /D "VIEWONLY" /D "NOTEST" /FR"ARMV4Rel/" /Fp"ARMV4Rel/BananaCE.pch" /YX /Fo"ARMV4Rel/" /O2 /MC /c 
"C:\Banana\RGISSmallFindCityToNumberConvert.cpp"
]
Creating command line "clarm.exe @C:\DOCUME~1\RTI~1.KAE\LOCALS~1\Temp\RSP80.tmp" 
一時ファイル "C:\DOCUME~1\RTI~1.KAE\LOCALS~1\Temp\RSP81.tmp" を作成し、次の内容を記録します
[
commctrl.lib coredll.lib aygshell.lib Ccrtrtti.lib /nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"WinMainCRTStartup" /incremental:no /pdb:"ARMV4Rel/BananaCE.pdb" /nodefaultlib:"libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib" /out:"ARMV4Rel/BananaCE.exe" /subsystem:windowsce,4.20 /align:"4096" /MACHINE:ARM 
.\ARMV4Rel\BAddressMatching.obj
.\ARMV4Rel\BBanana.obj
.\ARMV4Rel\BBananaConfig.obj
.\ARMV4Rel\BBananaConfigDlg.obj
.\ARMV4Rel\BClickMode.obj
.\ARMV4Rel\BConf.obj
.\ARMV4Rel\BFindAdressDlg.obj
.\ARMV4Rel\BFindEkiDlg.obj
.\ARMV4Rel\BGPSConfigDlg.obj
.\ARMV4Rel\BGPSInfoDlg.obj
.\ARMV4Rel\BGPSSettingDlg.obj
.\ARMV4Rel\BGPSStateDlg.obj
.\ARMV4Rel\BRotateMode.obj
.\ARMV4Rel\BUserDataEditDlg.obj
.\ARMV4Rel\BUserDataIconDlg.obj
.\ARMV4Rel\comm.obj
.\ARMV4Rel\main.obj
.\ARMV4Rel\RAlreadyException.obj
.\ARMV4Rel\RAutoLibraryWithException.obj
.\ARMV4Rel\RComboBox.obj
.\ARMV4Rel\RConferException.obj
.\ARMV4Rel\RConfigFile.obj
.\ARMV4Rel\RConv.obj
.\ARMV4Rel\RCreateFile.obj
.\ARMV4Rel\RDebug.obj
.\ARMV4Rel\RDialog.obj
.\ARMV4Rel\RDialogUtil.obj
.\ARMV4Rel\RDIBBitmap.obj
.\ARMV4Rel\RDoNotInitaliseException.obj
.\ARMV4Rel\RDrawObject.obj
.\ARMV4Rel\REdit.obj
.\ARMV4Rel\RException.obj
.\ARMV4Rel\RFileNotFoundException.obj
.\ARMV4Rel\RFileUtil.obj
.\ARMV4Rel\RFont.obj
.\ARMV4Rel\RFontCache.obj
.\ARMV4Rel\RGISCaption.obj
.\ARMV4Rel\RGISFindHintAddress.obj
.\ARMV4Rel\RGISFindHintEki.obj
.\ARMV4Rel\RGISGPS.obj
.\ARMV4Rel\RGISGPSLog.obj
.\ARMV4Rel\RGISMath.obj
.\ARMV4Rel\RGISMathAlgorithm.obj
.\ARMV4Rel\RGISNMEA0183.obj
.\ARMV4Rel\RGISSmall.obj
.\ARMV4Rel\RGISSmallAddress.obj
.\ARMV4Rel\RGISSmallChimei.obj
.\ARMV4Rel\RGISSmallDouro.obj
.\ARMV4Rel\RGISSmallDraw.obj
.\ARMV4Rel\RGISSmallDrawEffect.obj
.\ARMV4Rel\RGISSmallDupKill.obj
.\ARMV4Rel\RGISSmallFileRead.obj
.\ARMV4Rel\RGISSmallFindAddress.obj
.\ARMV4Rel\RGISSmallFindEki.obj
.\ARMV4Rel\RGISSmallFindObject.obj
.\ARMV4Rel\RGISSmallGlobalToBlock.obj
.\ARMV4Rel\RGISSmallHeaderImp.obj
.\ARMV4Rel\RGISSmallIntelligentCache.obj
.\ARMV4Rel\RGISSmallKawa.obj
.\ARMV4Rel\RGISSmallKoudo2.obj
.\ARMV4Rel\RGISSmallKoukyou.obj
.\ARMV4Rel\RGISSmallMaster.obj
.\ARMV4Rel\RGISSmallNameDatabase.obj
.\ARMV4Rel\RGISSmallParent.obj
.\ARMV4Rel\RGISSmallParentImp.obj
.\ARMV4Rel\RGISSmallPathFinder.obj
.\ARMV4Rel\RGISSmallPenFile.obj
.\ARMV4Rel\RGISSmallShareImage.obj
.\ARMV4Rel\RGISSmallSuiikiKai.obj
.\ARMV4Rel\RGISSmallTatemono.obj
.\ARMV4Rel\RGISSmallTetudo.obj
.\ARMV4Rel\RGISSmallType.obj
.\ARMV4Rel\RGISSmallUserData.obj
.\ARMV4Rel\RGISSmallUserDataFile.obj
.\ARMV4Rel\RGISSmallZyouti.obj
.\ARMV4Rel\RGraphics.obj
.\ARMV4Rel\RIOCannotCloseException.obj
.\ARMV4Rel\RIOCannotOpenException.obj
.\ARMV4Rel\RIOCannotReadException.obj
.\ARMV4Rel\RIOCannotWriteException.obj
.\ARMV4Rel\RIOException.obj
.\ARMV4Rel\RListenner.obj
.\ARMV4Rel\RListView.obj
.\ARMV4Rel\RMathAngle.obj
.\ARMV4Rel\RMessageBox.obj
.\ARMV4Rel\RNeoFile.obj
.\ARMV4Rel\RNeoIFStreamUtil.obj
.\ARMV4Rel\RNeoIStreamble.obj
.\ARMV4Rel\RNeoMemory.obj
.\ARMV4Rel\RNeoSerialPort.obj
.\ARMV4Rel\RNoComplateException.obj
.\ARMV4Rel\RNotFoundException.obj
.\ARMV4Rel\RNotSupportException.obj
.\ARMV4Rel\ROutOfRangeException.obj
.\ARMV4Rel\RParseException.obj
.\ARMV4Rel\RRegistry.obj
.\ARMV4Rel\RResorceImageLoad.obj
.\ARMV4Rel\RScrollBar.obj
.\ARMV4Rel\RState.obj
.\ARMV4Rel\RStdioFile.obj
.\ARMV4Rel\RStdioMemory.obj
.\ARMV4Rel\RStdioSerialPort.obj
.\ARMV4Rel\RStringRingBuffer.obj
.\ARMV4Rel\RSujiFontCache.obj
.\ARMV4Rel\RThread.obj
.\ARMV4Rel\RTimer.obj
.\ARMV4Rel\RToken.obj
.\ARMV4Rel\RWin32Exception.obj
.\ARMV4Rel\RWindow.obj
.\ARMV4Rel\RWindowBase.obj
.\ARMV4Rel\RZlib.obj
.\ARMV4Rel\WindowsMain.obj
.\ARMV4Rel\Banana.res
.\ARMV4Rel\RGISSmallFindCityToNumberConvert.obj
]
コマンド ライン "link.exe @C:\DOCUME~1\RTI~1.KAE\LOCALS~1\Temp\RSP81.tmp" の作成中
<h3>アウトプット ウィンドウ</h3>
コンパイル中...
RGISSmallFindCityToNumberConvert.cpp
リンク中...
一時ファイル "C:\DOCUME~1\RTI~1.KAE\LOCALS~1\Temp\RSP84.tmp" を作成し、次の内容を記録します
[
/nologo /o"ARMV4Rel/BananaCE.bsc" 
.\ARMV4Rel\BAddressMatching.sbr
.\ARMV4Rel\BBanana.sbr
.\ARMV4Rel\BBananaConfig.sbr
.\ARMV4Rel\BBananaConfigDlg.sbr
.\ARMV4Rel\BClickMode.sbr
.\ARMV4Rel\BConf.sbr
.\ARMV4Rel\BFindAdressDlg.sbr
.\ARMV4Rel\BFindEkiDlg.sbr
.\ARMV4Rel\BGPSConfigDlg.sbr
.\ARMV4Rel\BGPSInfoDlg.sbr
.\ARMV4Rel\BGPSSettingDlg.sbr
.\ARMV4Rel\BGPSStateDlg.sbr
.\ARMV4Rel\BRotateMode.sbr
.\ARMV4Rel\BUserDataEditDlg.sbr
.\ARMV4Rel\BUserDataIconDlg.sbr
.\ARMV4Rel\comm.sbr
.\ARMV4Rel\main.sbr
.\ARMV4Rel\RAlreadyException.sbr
.\ARMV4Rel\RAutoLibraryWithException.sbr
.\ARMV4Rel\RComboBox.sbr
.\ARMV4Rel\RConferException.sbr
.\ARMV4Rel\RConfigFile.sbr
.\ARMV4Rel\RConv.sbr
.\ARMV4Rel\RCreateFile.sbr
.\ARMV4Rel\RDebug.sbr
.\ARMV4Rel\RDialog.sbr
.\ARMV4Rel\RDialogUtil.sbr
.\ARMV4Rel\RDIBBitmap.sbr
.\ARMV4Rel\RDoNotInitaliseException.sbr
.\ARMV4Rel\RDrawObject.sbr
.\ARMV4Rel\REdit.sbr
.\ARMV4Rel\RException.sbr
.\ARMV4Rel\RFileNotFoundException.sbr
.\ARMV4Rel\RFileUtil.sbr
.\ARMV4Rel\RFont.sbr
.\ARMV4Rel\RFontCache.sbr
.\ARMV4Rel\RGISCaption.sbr
.\ARMV4Rel\RGISFindHintAddress.sbr
.\ARMV4Rel\RGISFindHintEki.sbr
.\ARMV4Rel\RGISGPS.sbr
.\ARMV4Rel\RGISGPSLog.sbr
.\ARMV4Rel\RGISMath.sbr
.\ARMV4Rel\RGISMathAlgorithm.sbr
.\ARMV4Rel\RGISNMEA0183.sbr
.\ARMV4Rel\RGISSmall.sbr
.\ARMV4Rel\RGISSmallAddress.sbr
.\ARMV4Rel\RGISSmallChimei.sbr
.\ARMV4Rel\RGISSmallDouro.sbr
.\ARMV4Rel\RGISSmallDraw.sbr
.\ARMV4Rel\RGISSmallDrawEffect.sbr
.\ARMV4Rel\RGISSmallDupKill.sbr
.\ARMV4Rel\RGISSmallFileRead.sbr
.\ARMV4Rel\RGISSmallFindAddress.sbr
.\ARMV4Rel\RGISSmallFindEki.sbr
.\ARMV4Rel\RGISSmallFindObject.sbr
.\ARMV4Rel\RGISSmallGlobalToBlock.sbr
.\ARMV4Rel\RGISSmallHeaderImp.sbr
.\ARMV4Rel\RGISSmallIntelligentCache.sbr
.\ARMV4Rel\RGISSmallKawa.sbr
.\ARMV4Rel\RGISSmallKoudo2.sbr
.\ARMV4Rel\RGISSmallKoukyou.sbr
.\ARMV4Rel\RGISSmallMaster.sbr
.\ARMV4Rel\RGISSmallNameDatabase.sbr
.\ARMV4Rel\RGISSmallParent.sbr
.\ARMV4Rel\RGISSmallParentImp.sbr
.\ARMV4Rel\RGISSmallPathFinder.sbr
.\ARMV4Rel\RGISSmallPenFile.sbr
.\ARMV4Rel\RGISSmallShareImage.sbr
.\ARMV4Rel\RGISSmallSuiikiKai.sbr
.\ARMV4Rel\RGISSmallTatemono.sbr
.\ARMV4Rel\RGISSmallTetudo.sbr
.\ARMV4Rel\RGISSmallType.sbr
.\ARMV4Rel\RGISSmallUserData.sbr
.\ARMV4Rel\RGISSmallUserDataFile.sbr
.\ARMV4Rel\RGISSmallZyouti.sbr
.\ARMV4Rel\RGraphics.sbr
.\ARMV4Rel\RIOCannotCloseException.sbr
.\ARMV4Rel\RIOCannotOpenException.sbr
.\ARMV4Rel\RIOCannotReadException.sbr
.\ARMV4Rel\RIOCannotWriteException.sbr
.\ARMV4Rel\RIOException.sbr
.\ARMV4Rel\RListenner.sbr
.\ARMV4Rel\RListView.sbr
.\ARMV4Rel\RMathAngle.sbr
.\ARMV4Rel\RMessageBox.sbr
.\ARMV4Rel\RNeoFile.sbr
.\ARMV4Rel\RNeoIFStreamUtil.sbr
.\ARMV4Rel\RNeoIStreamble.sbr
.\ARMV4Rel\RNeoMemory.sbr
.\ARMV4Rel\RNeoSerialPort.sbr
.\ARMV4Rel\RNoComplateException.sbr
.\ARMV4Rel\RNotFoundException.sbr
.\ARMV4Rel\RNotSupportException.sbr
.\ARMV4Rel\ROutOfRangeException.sbr
.\ARMV4Rel\RParseException.sbr
.\ARMV4Rel\RRegistry.sbr
.\ARMV4Rel\RResorceImageLoad.sbr
.\ARMV4Rel\RScrollBar.sbr
.\ARMV4Rel\RState.sbr
.\ARMV4Rel\RStdioFile.sbr
.\ARMV4Rel\RStdioMemory.sbr
.\ARMV4Rel\RStdioSerialPort.sbr
.\ARMV4Rel\RStringRingBuffer.sbr
.\ARMV4Rel\RSujiFontCache.sbr
.\ARMV4Rel\RThread.sbr
.\ARMV4Rel\RTimer.sbr
.\ARMV4Rel\RToken.sbr
.\ARMV4Rel\RWin32Exception.sbr
.\ARMV4Rel\RWindow.sbr
.\ARMV4Rel\RWindowBase.sbr
.\ARMV4Rel\RZlib.sbr
.\ARMV4Rel\WindowsMain.sbr
.\ARMV4Rel\RGISSmallFindCityToNumberConvert.sbr]
コマンド ライン "bscmake.exe @C:\DOCUME~1\RTI~1.KAE\LOCALS~1\Temp\RSP84.tmp" の作成中
ブラウザ データベースを作成中...
<h3>アウトプット ウィンドウ</h3>




<h3>結果</h3>
BananaCE.exe - エラー 0、警告 0
</pre>
</body>
</html>
